require:
  - 'rubocop/minitest'
  - 'rubocop-thread_safety'

inherit_gem:
  rubocop-ruby2_0: rubocop.yml

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true # Display the name of the failing cops

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing
Layout/IndentHeredoc:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_context
    - shared_examples
    - shared_examples_for
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
