name: Supported Rubies

on:
  push:
    branches:
      - master
      - '*-maintenance'
      - '*-dev'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - truffleruby-head
          - ruby-head
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get -y --fix-missing install libcurl4-openssl-dev
      - name: Setup Ruby & Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
