name: Code Style Checks

on:
  push:
    branches:
      - master
      - '*-maintenance'
      - '*-dev'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    name: Rubocop
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby & Bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop -DESP
